WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-05-06 19:29:03,722	WARNING worker.py:1373 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/tune/logger.py:133: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/tune/logger.py:138: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2020-05-06 19:29:04,195	ERROR log_sync.py:34 -- Log sync requires cluster to be setup with `ray up`.
2020-05-06 19:29:04,213	WARNING ppo.py:143 -- FYI: By default, the value function will not share layers with the policy model ('vf_share_layers': False).
2020-05-06 19:29:04.233808: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-05-06 19:29:04.301399: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1299975000 Hz
2020-05-06 19:29:04.304483: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555559510170 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-06 19:29:04.304799: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-06 19:29:04.442446: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-06 19:29:04.548140: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-05-06 19:29:04.549723: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nid03395): /proc/driver/nvidia/version does not exist
WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:77: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.random.categorical` instead.
WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:64: calling reduce_max_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:69: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2020-05-06 19:30:13,828	INFO trainable.py:105 -- _setup took 69.624 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2020-05-06 19:30:13,847	WARNING util.py:47 -- Install gputil for GPU system monitoring.
WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/policy/tf_policy.py:570: Variable.load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Variable.assign which has equivalent behavior in 2.X.
2020-05-06 19:35:18,813	ERROR worker.py:1716 -- listen_error_messages_raylet: Connection closed by server.
***********************************************************
Nodes used: 4
Available resources: {'CPU': 4.0}
***********************************************************
Scalar value :  0.14427932477276006
[2m[36m(pid=58104, ip=10.236.16.130)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
[2m[36m(pid=58104, ip=10.236.16.130)[0m Instructions for updating:
[2m[36m(pid=58104, ip=10.236.16.130)[0m non-resource variables are not supported in the long term
[2m[36m(pid=58039)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
[2m[36m(pid=58039)[0m Instructions for updating:
[2m[36m(pid=58039)[0m non-resource variables are not supported in the long term
[2m[36m(pid=58104, ip=10.236.16.130)[0m 2020-05-06 19:29:54.109450: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
[2m[36m(pid=58104, ip=10.236.16.130)[0m Scalar value :  0.14427932477276006
[2m[36m(pid=58104, ip=10.236.16.130)[0m 2020-05-06 19:29:54.215933: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1300130000 Hz
[2m[36m(pid=58104, ip=10.236.16.130)[0m 2020-05-06 19:29:54.218627: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55555946e400 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[2m[36m(pid=58104, ip=10.236.16.130)[0m 2020-05-06 19:29:54.218768: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[2m[36m(pid=58104, ip=10.236.16.130)[0m 2020-05-06 19:29:54.398329: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
[2m[36m(pid=58039)[0m 2020-05-06 19:29:54.528682: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
[2m[36m(pid=58039)[0m Scalar value :  0.14427932477276006
[2m[36m(pid=58104, ip=10.236.16.130)[0m 2020-05-06 19:29:54.554698: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
[2m[36m(pid=58104, ip=10.236.16.130)[0m 2020-05-06 19:29:54.554901: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nid04225): /proc/driver/nvidia/version does not exist
[2m[36m(pid=58039)[0m 2020-05-06 19:29:54.638788: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1299915000 Hz
[2m[36m(pid=58039)[0m 2020-05-06 19:29:54.641504: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55555946e2c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[2m[36m(pid=58039)[0m 2020-05-06 19:29:54.641685: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[2m[36m(pid=58039)[0m 2020-05-06 19:29:54.821301: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
[2m[36m(pid=58104, ip=10.236.16.130)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
[2m[36m(pid=58104, ip=10.236.16.130)[0m Instructions for updating:
[2m[36m(pid=58104, ip=10.236.16.130)[0m If using Keras pass *_constraint arguments to layers.
[2m[36m(pid=58039)[0m 2020-05-06 19:29:54.979523: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
[2m[36m(pid=58039)[0m 2020-05-06 19:29:54.980343: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nid04227): /proc/driver/nvidia/version does not exist
[2m[36m(pid=58039)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
[2m[36m(pid=58039)[0m Instructions for updating:
[2m[36m(pid=58039)[0m If using Keras pass *_constraint arguments to layers.
[2m[36m(pid=58104, ip=10.236.16.130)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:77: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
[2m[36m(pid=58104, ip=10.236.16.130)[0m Instructions for updating:
[2m[36m(pid=58104, ip=10.236.16.130)[0m Use `tf.random.categorical` instead.
[2m[36m(pid=58039)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:77: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
[2m[36m(pid=58039)[0m Instructions for updating:
[2m[36m(pid=58039)[0m Use `tf.random.categorical` instead.
[2m[36m(pid=58104, ip=10.236.16.130)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:64: calling reduce_max_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[2m[36m(pid=58104, ip=10.236.16.130)[0m Instructions for updating:
[2m[36m(pid=58104, ip=10.236.16.130)[0m keep_dims is deprecated, use keepdims instead
[2m[36m(pid=58104, ip=10.236.16.130)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:69: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[2m[36m(pid=58104, ip=10.236.16.130)[0m Instructions for updating:
[2m[36m(pid=58104, ip=10.236.16.130)[0m keep_dims is deprecated, use keepdims instead
[2m[36m(pid=58104, ip=10.236.16.130)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
[2m[36m(pid=58104, ip=10.236.16.130)[0m Instructions for updating:
[2m[36m(pid=58104, ip=10.236.16.130)[0m Use tf.where in 2.0, which has the same broadcast rule as np.where
[2m[36m(pid=58039)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:64: calling reduce_max_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[2m[36m(pid=58039)[0m Instructions for updating:
[2m[36m(pid=58039)[0m keep_dims is deprecated, use keepdims instead
[2m[36m(pid=58039)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:69: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[2m[36m(pid=58039)[0m Instructions for updating:
[2m[36m(pid=58039)[0m keep_dims is deprecated, use keepdims instead
[2m[36m(pid=58039)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
[2m[36m(pid=58039)[0m Instructions for updating:
[2m[36m(pid=58039)[0m Use tf.where in 2.0, which has the same broadcast rule as np.where
[2m[36m(pid=48633)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
[2m[36m(pid=48633)[0m Instructions for updating:
[2m[36m(pid=48633)[0m non-resource variables are not supported in the long term
Performing iteration: 0
[2m[36m(pid=58104, ip=10.236.16.130)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/policy/tf_policy.py:570: Variable.load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
[2m[36m(pid=58104, ip=10.236.16.130)[0m Instructions for updating:
[2m[36m(pid=58104, ip=10.236.16.130)[0m Prefer Variable.assign which has equivalent behavior in 2.X.
[2m[36m(pid=58039)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/policy/tf_policy.py:570: Variable.load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
[2m[36m(pid=58039)[0m Instructions for updating:
[2m[36m(pid=58039)[0m Prefer Variable.assign which has equivalent behavior in 2.X.
[2m[36m(pid=48633)[0m 2020-05-06 19:30:18.948908: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
[2m[36m(pid=48633)[0m Scalar value :  0.14427932477276006
[2m[36m(pid=57967, ip=10.236.16.110)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
[2m[36m(pid=57967, ip=10.236.16.110)[0m Instructions for updating:
[2m[36m(pid=57967, ip=10.236.16.110)[0m non-resource variables are not supported in the long term
[2m[36m(pid=48633)[0m 2020-05-06 19:30:19.089974: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1299975000 Hz
[2m[36m(pid=48633)[0m 2020-05-06 19:30:19.118004: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55555946e3d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[2m[36m(pid=48633)[0m 2020-05-06 19:30:19.118159: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[2m[36m(pid=48633)[0m 2020-05-06 19:30:19.154645: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
[2m[36m(pid=48633)[0m 2020-05-06 19:30:19.226162: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
[2m[36m(pid=48633)[0m 2020-05-06 19:30:19.226364: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nid03395): /proc/driver/nvidia/version does not exist
[2m[36m(pid=48633)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
[2m[36m(pid=48633)[0m Instructions for updating:
[2m[36m(pid=48633)[0m If using Keras pass *_constraint arguments to layers.
[2m[36m(pid=48633)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:77: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
[2m[36m(pid=48633)[0m Instructions for updating:
[2m[36m(pid=48633)[0m Use `tf.random.categorical` instead.
[2m[36m(pid=48633)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:64: calling reduce_max_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[2m[36m(pid=48633)[0m Instructions for updating:
[2m[36m(pid=48633)[0m keep_dims is deprecated, use keepdims instead
[2m[36m(pid=48633)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:69: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[2m[36m(pid=48633)[0m Instructions for updating:
[2m[36m(pid=48633)[0m keep_dims is deprecated, use keepdims instead
[2m[36m(pid=48633)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
[2m[36m(pid=48633)[0m Instructions for updating:
[2m[36m(pid=48633)[0m Use tf.where in 2.0, which has the same broadcast rule as np.where
[2m[36m(pid=57967, ip=10.236.16.110)[0m Scalar value :  0.14427932477276006
[2m[36m(pid=57967, ip=10.236.16.110)[0m 2020-05-06 19:30:25.023515: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
[2m[36m(pid=57967, ip=10.236.16.110)[0m 2020-05-06 19:30:25.130349: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1299915000 Hz
[2m[36m(pid=57967, ip=10.236.16.110)[0m 2020-05-06 19:30:25.133090: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55555946e780 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[2m[36m(pid=57967, ip=10.236.16.110)[0m 2020-05-06 19:30:25.133237: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[2m[36m(pid=57967, ip=10.236.16.110)[0m 2020-05-06 19:30:25.307131: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
[2m[36m(pid=57967, ip=10.236.16.110)[0m 2020-05-06 19:30:25.462033: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
[2m[36m(pid=57967, ip=10.236.16.110)[0m 2020-05-06 19:30:25.462224: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nid04058): /proc/driver/nvidia/version does not exist
[2m[36m(pid=57967, ip=10.236.16.110)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
[2m[36m(pid=57967, ip=10.236.16.110)[0m Instructions for updating:
[2m[36m(pid=57967, ip=10.236.16.110)[0m If using Keras pass *_constraint arguments to layers.
[2m[36m(pid=57967, ip=10.236.16.110)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:77: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
[2m[36m(pid=57967, ip=10.236.16.110)[0m Instructions for updating:
[2m[36m(pid=57967, ip=10.236.16.110)[0m Use `tf.random.categorical` instead.
[2m[36m(pid=57967, ip=10.236.16.110)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:64: calling reduce_max_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[2m[36m(pid=57967, ip=10.236.16.110)[0m Instructions for updating:
[2m[36m(pid=57967, ip=10.236.16.110)[0m keep_dims is deprecated, use keepdims instead
[2m[36m(pid=57967, ip=10.236.16.110)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/models/tf/tf_action_dist.py:69: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
[2m[36m(pid=57967, ip=10.236.16.110)[0m Instructions for updating:
[2m[36m(pid=57967, ip=10.236.16.110)[0m keep_dims is deprecated, use keepdims instead
[2m[36m(pid=57967, ip=10.236.16.110)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
[2m[36m(pid=57967, ip=10.236.16.110)[0m Instructions for updating:
[2m[36m(pid=57967, ip=10.236.16.110)[0m Use tf.where in 2.0, which has the same broadcast rule as np.where
[2m[36m(pid=48633)[0m WARNING:tensorflow:From /home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/policy/tf_policy.py:570: Variable.load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
[2m[36m(pid=48633)[0m Instructions for updating:
[2m[36m(pid=48633)[0m Prefer Variable.assign which has equivalent behavior in 2.X.
2020-05-06 19:35:18,814	ERROR import_thread.py:89 -- ImportThread: Connection closed by server.
2020-05-06 19:35:18,823	ERROR worker.py:1616 -- print_logs: Connection closed by server.
2020-05-06 19:35:18,966	WARNING worker.py:1553 -- Could not push exception to redis.
Traceback (most recent call last):
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/worker.py", line 2372, in wait
    worker.current_task_id,
  File "python/ray/_raylet.pyx", line 271, in ray._raylet.RayletClient.wait
  File "python/ray/_raylet.pyx", line 61, in ray._raylet.check_status
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/exceptions.py", line 86, in __init__
    def __init__(self, client_exc):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ppo.py", line 137, in <module>
    result = trainer.train()
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 358, in train
    result = Trainable.train(self)
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/tune/trainable.py", line 171, in train
    result = self._train()
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 126, in _train
    fetches = self.optimizer.step()
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 140, in step
    self.num_envs_per_worker, self.train_batch_size)
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/rllib/optimizers/rollout.py", line 27, in collect_samples
    [fut_sample], _ = ray.wait(list(agent_dict))
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/worker.py", line 2374, in wait
    return ready_ids, remaining_ids
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/profiling.py", line 185, in __exit__
    "traceback": str(traceback.format_exc()),
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/traceback.py", line 364, in extract
    f.line
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/traceback.py", line 286, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/linecache.py", line 95, in updatecache
    stat = os.stat(fullname)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/rmaulik/.conda/envs/rllib_env/lib/python3.6/site-packages/ray/worker.py", line 1518, in shutdown
KeyboardInterrupt
